package test.demo;
// IMPORT LIBRARY PACKAGES NEEDED BY YOUR PROGRAM
// SOME CLASSES WITHING A PACKAGE MAY BE RESTRICTED
// DEFIND ANY CLASS AND METHOD NEEDED
// CLASS BEGINS, THIS CLASS IS REQUIRED
class GCD {
	// METHOD SIGNATURE BEGINS, THIS METHOD IS REQUIRED
	public int generalizedGCD(int num, int[] arr) {
		// WRITE YOUR CODE HERE
		return 0;
	}
	// METHOD SIGNATURE ENDS
}
